version: '3'
services:
  game_server:
    image: presidents.azurecr.io/presidents_game_server:latest
    ports:
      - target: 8000
    restart: always
  
  game_god:
    image: presidents.azurecr.io/presidents_game_god:latest
    restart: always

  game_store:
    image: presidents.azurecr.io/redis:latest
    restart: always
  
  socketio_pubsub:
    image: presidents.azurecr.io/redis:latest
    restart: always
