version: '3.7'
services:
  game_store:
    image: "redis:6.0-rc-buster"
    ports:
      - target: 6379
        published: 6379
    restart: always
  
  socketio_pubsub:
    image: "redis:6.0-rc-buster"
    ports:
      - target: 6379
        published: 6380
    restart: always

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  data_stream:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      # # https://rmoff.net/2018/08/02/kafka-listeners-explained/
      # - KAFKA_CFG_LISTENERS=stream_processor://data_stream:9092
      # - KAFKA_CFG_ADVERTISED_LISTENERS=stream_processor://data_stream:9092
      # - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=stream_processor:PLAINTEXT
      # - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=stream_processor
    ports:
      - target: 9092
        published: 9092

  # stream_processor:
  #   build:
  #     context: ./
  #     dockerfile: ./src/back/data/stream/Dockerfile
  #   depends_on:
  #     - data_stream
  #   volumes:
  #     - /src/back:/src/back

  game_server:
    build:
      context: ./  # runs the Dockerfile as if from workspace dir
      dockerfile: ./src/back/server/game_server/Dockerfile
    depends_on:
      - game_store
      - socketio_pubsub
    ports:
      - target: 8000
        published: 8000
    volumes:
      - ./src/back:/src/back
    restart: always
    
  
  game_god:
    build:
      context: ./
      dockerfile: ./src/back/server/game_god/Dockerfile
    depends_on:
      - game_store
      - socketio_pubsub
    ports:
      - target: 8000
        published: 8001
    volumes:
      - ./src/back:/src/back
    restart: always
    stdin_open: true
    tty: true
    
