name: pres
dependencies:
  - python=3.7
  - flask
  - flask-socketio
  - numpy
  - mypy_extensions
  - pytables
  - pip:
    - gunicorn
    - bidict
    - llist
    - deepdish
    - xxhash
    - eventlet
  